JSONSetElement (""; 

  ["GROUP"; $TEST_GROUP; JSONString];
  ["RESULT"; $TEST_SCRIPT_RESULT; ""];
  ["NAME"; $TEST_NAME; JSONString];
  ["PARAMETER"; $TEST_PARAMETER; ""];
  ["ASERTION"; $TEST_ASSERTION; JSONString];
  ["EXPECTED"; $TEST_RESULT_EXPECTED; ""] ;
  ["ACTUAL"; $TEST_RESULT_ACTUAL; ""] 
)

JSONSetElement (""; 

  ["GROUP"; $TEST_GROUP; JSONString];
  ["SCRIPT_RESULT"; $TEST_SCRIPT_RESULT; ""];
  ["NAME"; $TEST_NAME; JSONString];
  ["PARAMETER"; $TEST_PARAMETER; ""];
  ["DESCRIPTION"; $TEST_DESCRIPTION; JSONString];
  ["RESULT_EXPECTED"; $TEST_RESULT_EXPECTED; ""] ;
  ["RESULT_ACTUAL"; $TEST_RESULT_ACTUAL; ""] 
)


SCRIPT_RESULT -> RESULT
DESCRIPTION => ASERTION

RESULT_EXPECTED = EXPECTED
RESULT_ACTUAL = ACTUAL